### ISSUE TITLE
Readme file correction

### ISSUE THREAD

**Issue by moritzengineering** [themesberg/flowbite-svelte-blocks#37]
the install line in Readme file is missing the  flowbite-svelte-blocks module

pnpm i flowbite flowbite-svelte tailwind-merge @floating-ui/dom flowbite-svelte-icons
must be
pnpm i flowbite flowbite-svelte tailwind-merge @floating-ui/dom flowbite-svelte-icons  flowbite-svelte-blocks

**Comment by shinokada** [comment]
I will update dependencies so that we don't need all of these.
