### ISSUE TITLE
CheckSolid and ChevronRightSolid icon update to ChevronRightOutline and CheckOutline

### ISSUE THREAD

**Issue by NathanielRand** [themesberg/flowbite-svelte-blocks#55]
### Describe the bug

CheckSolid and ChevronRightSolid are longer on [Flowbite Svelte Icons](https://flowbite-svelte-icons.codewithshin.com/solid). The Solid version of these icons are still being referenced here:

- News.svelte
- PricingItem.svelte

Error:
![image](https://github.com/themesberg/flowbite-svelte-blocks/assets/16087849/83707004-8126-463a-94d9-918a3a6f4a4b)

### Reproduction

Repo: [my-app](https://github.com/NathanielRand/my-app)

Any standard quickstart repo will do the trick. May require hard reload to produce error log

### Flowbite version and System Info

```shell
Flowbite v2.2.1
Flowbite Svelte v0.44.22
```

**Comment by shinokada** [comment]
The latest version doesn't use them.
Are you using the latest?

**Comment by AirZona** [comment]
Getting the same, using the latest as well...

`
"flowbite-svelte": "^0.44.24",
"flowbite-svelte-blocks": "^1.1.0",
"flowbite-svelte-icons": "^1.5.0",
`

**Comment by AirZona** [comment]
@NathanielRand yea, needs a new release tag.

**Comment by RDKeith** [comment]
Had the same issue just rear its head for me.  Had to revert to a previous version to get it working.  Hoping this is updated soon, please!

**Comment by shinokada** [comment]
Can you install the latest and let me know.

```
pnpm i -D flowbite-svelte-blocks@latest
```

**Comment by NathanielRand** [comment]
> Can you install the latest and let me know.
> 
> ```
> pnpm i -D flowbite-svelte-blocks@latest
> ```

Confirmed this now works correctly. Thank you

**Comment by NathanielRand** [comment]
> Can you install the latest and let me know.
> 
> ```
> pnpm i -D flowbite-svelte-blocks@latest
> ```

Confirmed this now works correctly. Thank you
